# .github/workflows/aws-deploy.yml
name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate deployment package
      run: zip -r deploy.zip * -x "*.git*"
      
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: multi-cloud-cicd-demo
        environment_name: multi-cloud-cicd-demo-env
        region: ap-south-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        wait_for_environment_recovery: 60