name: Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  SecurityQuality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Vulnerability Scan (npm audit)
        run: npm audit

      - name: Run ESLint for Code Quality
        run: npx eslint .

      - name: Run Tests with Coverage
        run: npm test -- --coverage
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Init:
    runs-on: ubuntu-latest
    needs: SecurityQuality
    steps:
      - uses: actions/checkout@v3
      - name: Azure Init
        run: echo "Initializing Azure deployment..."

  Build:
    runs-on: ubuntu-latest
    needs: Init
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

  Stage:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - name: Azure Stage
        run: echo "Staging Azure deployment..."

  Deploy:
    runs-on: ubuntu-latest
    needs: Stage
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .