name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]

jobs:
  SecurityQuality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        
      - name : Install express
        run: npm install express

      - name: Run Vulnerability Scan (npm audit)
        run: npm audit

      - name: Run ESLint for Code Quality
        run: npx eslint .

      - name: Run Tests with Coverage
        run: npm test -- --coverage
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Init:
    runs-on: ubuntu-latest
    needs: SecurityQuality
    steps:
      - uses: actions/checkout@v3
      - name: GCP Init
        run: echo "Initializing GCP deployment..."

  Build:
    runs-on: ubuntu-latest
    needs: Init
    steps:
      - uses: actions/checkout@v3
      - name: Set lowercase repository name
        id: setrepo
        run: echo "REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

  Stage:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - name: GCP Stage
        run: echo "Staging GCP deployment..."

  Deploy:
    runs-on: ubuntu-latest
    needs: Stage
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy myapp \
            --image ghcr.io/${{ env.REPO }}:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --quiet